#!/usr/bin/env bash

SPARKLE_VERSION="${SPARKLE_VERSION:-2.9.0}"
SPARKLE_KEY_ACCOUNT="${SPARKLE_KEY_ACCOUNT:-sg.tk.JustNow}"
SPARKLE_SITE_URL="${SPARKLE_SITE_URL:-https://justnow.tk.sg}"
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-${SPARKLE_SITE_URL%/}/appcast.xml}"
SPARKLE_RELEASES_URL="${SPARKLE_RELEASES_URL:-${SPARKLE_SITE_URL%/}/releases/}"
SPARKLE_RELEASE_DOWNLOAD_BASE_URL="${SPARKLE_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/yjsoon/justnow/releases/download}"
SPARKLE_TOOLS_REPO="${SPARKLE_TOOLS_REPO:-sparkle-project/Sparkle}"
SPARKLE_TOOLS_ARCHIVE="${SPARKLE_TOOLS_ARCHIVE:-Sparkle-${SPARKLE_VERSION}.tar.xz}"
SPARKLE_TOOLS_CACHE_DIR="${SPARKLE_TOOLS_CACHE_DIR:-build/sparkle-tools/${SPARKLE_VERSION}}"
